apiVersion: v1
kind: Service
metadata:
  name: prediction-creator-service
spec:
  selector:
    app: prediction-creator
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
