apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-module
  template:
    metadata:
      labels:
        app: create-module
    spec:
      containers:
      - name: create-module
        image: alextno/create_module_kube:latest
        ports:
        - containerPort: 5000
