apiVersion: v1
kind: Service
metadata:
  name: instance-creator-service
spec:
  type: ClusterIP
  selector:
    app: instance-creator
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
